# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build 
- task: CmdLine@2
  inputs:
    script: 'echo $buildConfiguration'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo ' Present working directory is $System.DefaultWorkingDirectory'
      echo ' Artifact directory is $Build.ArtifactStagingDirectory'
- task: UseDotNet@2
  displayName: Set dotnet sdk
  inputs:
    packageType: 'sdk'
    version: '2.x'
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: Set dotnet runtime
  inputs:
    packageType: 'runtime'
    version: '2.x'
    includePreviewVersions: true

- task: NuGetCommand@2
  displayName: Nuget restore
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'pipelines-dotnet-core.csproj'

- task: PublishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'



